### ISSUE TITLE
How should I solve this problem?

### ISSUE THREAD

**Issue by Run2948** [Lanesra712/Danvic.PSU#1]
The 'MySQLNumberTypeMapping' does not support value conversions. Support for value conversions typically requires changes in the database provider.

**Comment by danvic712** [comment]
Sorry for later to reply it, this issure may cased by MySQL provider issue,you can use Pomelo.EntityFrameworkCore.MySql to instead of MySql.Data.EntityFrameworkCore  or do not update MySQL  driver components , this address may help you [https://github.com/aspnet/EntityFrameworkCore/issues/12344](https://github.com/aspnet/EntityFrameworkCore/issues/12344) @Run2948

**Comment by myzdashen** [comment]
![a4thuz7egs80z 4l mz6q5](https://user-images.githubusercontent.com/22787632/50649134-0b548b80-0fb8-11e9-94d2-73d236148e69.png)
这个问题是啥啊，搞了半天没搞懂

**Comment by danvic712** [comment]
这个你可以看从系统记录的日志信息中看是哪里出错了，日志文件在 c:\temp\jixia\ 下面，这个应该是无法连接到 MySQL 导致的@myzdashen

**Comment by myzdashen** [comment]
现在启动的时候都没有进Startup文件里面的方法

**Comment by myzdashen** [comment]
可以用SQL server数据库的吧？
